wandb_version: 1

layer_1:
  desc: null
  value: 512
activation_1:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.7479842380417552
layer_2:
  desc: null
  value: 10
activation_2:
  desc: null
  value: softmax
optimizer:
  desc: null
  value: sgd
loss:
  desc: null
  value: sparse_categorical_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710323919.261158
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 5
      13: darwin-arm64
